### ISSUE TITLE
fonts: *Emphasis* not shown as italics because of David CLM

### ISSUE THREAD

**Issue by cben** [cben/mathdown#198]
Chrome, Fedora 30.  
https://www.mathdown.net/?doc=CTrq2WEaURk#Test-italics-emphasis
![www mathdown net__doc=CTrq2WEaURk(iPhone 5_SE)](https://user-images.githubusercontent.com/273688/76703666-bfcd5f80-66db-11ea-8bb8-4cc80baf936c.png)

It seems I have neither Georgia nor Bitstream Charter, next fonts are David, David CLM (which I added as "not bad" Hebrew serif fonts), and the latter contains english letters, but they're upright, not italic :cry: 
Note the left-leaning parentheses — David CLM has left-leaning italics for hebrew letters and punctuation.  And I suspect it _deliberately_ made English upright to avoid visual clash of left/right leaning letters?

**Comment by cben** [comment]
I guess I need to drop David because Hebrew is frequently mixed with latin text (especially in mathdown's case of intermixing math), and slanting to the left is not going to work well.

(article about slanting in hebrew: https://www.typotheque.com/articles/secondary_style_in_hebrew_typography)

**Comment by cben** [comment]
Needless to say prioritizing Hebrew, when weak bidi makes it barely usable, over English is a no-no.  I'm also aware that Culmus and other libre fonts are a small corner compared to 

test pages for tons of herbrew fonts:
- https://languagegardenblog.wordpress.com/2017/06/07/hebrew-fonts/
  (to make everything italic, run `document.body.style.fontStyle="italic"` in JS console)
- https://opensiddur.org/help/fonts/

Omitting _David CLM_ on my computer results in hebrew letters falling back to `serif` = _Liberation Serif_:
![www mathdown net__doc=CTrq2WEaURk](https://user-images.githubusercontent.com/273688/76705156-9b2ab500-66e6-11ea-93a6-931e4e0ffedb.png)
which works :heavy_check_mark: but the hebrew looks singnificantly worse IMO, at least at this size :-(

_Frank Ruehl CLM_ looks better, except it takes over English letters too, and is too small compared doesn't other font sizes e.g. monospace:
![www mathdown net__doc=CTrq2WEaURk](https://user-images.githubusercontent.com/273688/76705214-07a5b400-66e7-11ea-8bdd-09514000e175.png)
That's not a blocker — could use unicode-range — but needs testing.

_Shofar_ and _Hadasim CLM_ also take over punctuation and English letters — with a left slant!
![www mathdown net__doc=CTrq2WEaURk](https://user-images.githubusercontent.com/273688/76711883-21adb980-671c-11ea-81d6-47ce52a99eff.png)
![www mathdown net__doc=CTrq2WEaURk](https://user-images.githubusercontent.com/273688/76711976-14dd9580-671d-11ea-9e0f-718671c932b1.png)
Amusing, but no :-)

_Miriam CLM_ is not bad actually, but too different from other serif fonts.
![www mathdown net__doc=CTrq2WEaURk](https://user-images.githubusercontent.com/273688/76712054-d85e6980-671d-11ea-84a1-b015c54eb0f0.png)

**Comment by cben** [comment]
Here's a weird hack!  Use David but force browser to use "faux oblique", slanted to the *right*!
Also applied `unicode-range` to stop affecting other scripts.
![_home_cben_md_mathdown_index html_doc=CTrq2WEaURk](https://user-images.githubusercontent.com/273688/76732968-8858c480-6768-11ea-9a43-bcbceaba989e.png)
=> #199

**Comment by cben** [comment]
~~hmm, hack may not work, this simply fell back on `serif` = _Linux Libertine_.  investigating...~~

**Comment by anpc** [comment]
Conversely, on an Ubuntu with both Georgia and Charter installed, Georgia is getting used for punctuation which looks bad mixed with Hebrew — note the parentheses in "הדגשה (נטוי)‏" going slanting in opposite direction:
![www mathdown net__doc=CTrq2WEaURk(iPhone 5_SE)](https://user-images.githubusercontent.com/4655504/76737602-c1e1fd80-6771-11ea-8433-508c19e2beee.png)
