### ISSUE TITLE
gitit or ikiwiki interoperability

### ISSUE THREAD

**Issue by cben** [cben/mathdown#99]
ikiwiki is somewhat close to my goals here, and it would be neat to maximize interoperability.
Not sure how specifically. 
- shared comments syntax (#41)?
- wikilinks to jump between pages?  opened separate issue #98.
- Could it be possible to use mathdown as a real-time editing frontend to git-backed ikiwiki?  It's impractical to commit every keystroke, but periodic not-precisely-attributed JotGit-style commits are probably OK.  That could go part way to resolve #4 (but is the real-time part still in Firebase)?

**Comment by anpc** [comment]
Actually, gitit might be a better match than ikiwiki (being pandoc-based and supporting math out of the box rather than with 3rd-party plugins).

**Comment by cben** [comment]
[opened #103 to discuss using real version-control as backend; this issue is about format/feature interoperability.]
